### ISSUE TITLE
problem z utworzeniem folderu

### ISSUE THREAD

**Issue by iiaawaak** [RouNNdeL/korona-science#1]
Pojawia sie taki komunikat
![Przechwytywanie](https://user-images.githubusercontent.com/62105841/76528116-95c43500-6470-11ea-9e5f-944a55d420ba.PNG)

**Comment by RouNNdeL** [comment]
Uruchomiłeś/aś jupytera w folderze system32. Przed uruchomieniem upewnij się, że wiersz polecenia wskazuje na katalog domowy lub pulpit.

![image](https://user-images.githubusercontent.com/22538735/76528342-eb98dd00-6470-11ea-869c-163c91da7c07.png)

**Comment by RouNNdeL** [comment]
Najlepiej uruchomić nowy wiersz polecenia bez uprawnień Administratora

**Comment by iiaawaak** [comment]
![Przechwytywanie](https://user-images.githubusercontent.com/62105841/76528712-88f41100-6471-11ea-8949-180fc63eea85.PNG)
nowy wiersz pokazuje taka lokalizację (nie mam w ogóle uprawnień administratora na komputerze)

**Comment by iiaawaak** [comment]
A zmienić wskazywanie na pulpit?

**Comment by RouNNdeL** [comment]
w takim razie nalezy zmienic sciezke za pomocą polecenia `cd C:\Users\<user>\Desktop`. gdzie `<user>` to twoja nazwa uzytkownika w windows

**Comment by iiaawaak** [comment]
![Przechwytywanie](https://user-images.githubusercontent.com/62105841/76529414-89d97280-6472-11ea-8c29-51371159e87e.PNG)

**Comment by RouNNdeL** [comment]
Ponieważ masz spacje w nazwie użytkownika musisz cala ścieżkę zamknąć w cudzysłów. 
`cd "C:\Users..."`

**Comment by iiaawaak** [comment]
![Przechwytywanie](https://user-images.githubusercontent.com/62105841/76530213-b2ae3780-6473-11ea-80a6-d604031499d8.PNG)
Wciąż ten sam problem :(

**Comment by RouNNdeL** [comment]
w takim razie otworz docelowy katalog w eksploratorze plikow, a nastepnie Shift+prawy przycisk myszy -> otworz okno polecenia tutaj.

**Comment by iiaawaak** [comment]
Mam opcję otworzenia w taki sposób tylko Windows Powershell  - czy nie będzie różnicy?

**Comment by iiaawaak** [comment]
Chyba nie - udało się utworzyć folder.
Wielkie dzięki za pomoc 🥇
